name: Build EspressoLauncher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew (Linux & macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build and package
        run: |
          # Set installer type per OS
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            ./gradlew clean jlink jpackage -PinstallerType=deb
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            ./gradlew clean jlink jpackage -PinstallerType=exe
          else
            ./gradlew clean jlink jpackage -PinstallerType=dmg
          fi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: EspressoLauncher-${{ matrix.os }}
          path: build/jpackage/
