name: Build EspressoLauncher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Use a dynamic runner based on the matrix OS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Define the combinations of OS and installer types
        include:
          - os: ubuntu-latest
            installerType: deb
          - os: ubuntu-latest
            installerType: rpm
          - os: windows-latest
            installerType: exe
          - os: macos-latest
            installerType: dmg

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew (Linux & macOS)
        # This step runs only if the runner OS is not Windows
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build and package ${{ matrix.installerType }}
        # The installerType is now directly passed from the matrix
        run: ./gradlew clean jlink jpackage -PinstallerType=${{ matrix.installerType }}

      - name: Upload installer artifact
        # Updated to v4 to resolve deprecation warning
        uses: actions/upload-artifact@v4
        with:
          # Name the artifact uniquely using both OS and installer type
          name: EspressoLauncher-${{ matrix.os }}-${{ matrix.installerType }}
          path: build/jpackage/
